name = "contentps-test"
[defaults]
builder = "exec:go"
runner = "local:exec"

[builders."docker:go"]
enabled = true
go_version = "1.16"
module_path = "github.com/pedroaston/contentps-test"
exec_pkg = "."

[builders."exec:go"]
enabled = true
module_path = "github.com/pedroaston/contentps-test"

[runners."local:docker"]
enabled = true

[runners."local:exec"]
enabled = true

[runners."cluster:k8s"]
enabled = true

[[testcases]]
name= "firstTry"
instances = { min = 1, max = 5, default = 1 }