[metadata]
  name = "contentps-test"
  author = "pedroaston"

[global]
  plan = "contentps-test"
  case = "complete-scout-test"
  total_instances = 100
  builder = "docker:go"
  runner = "local:docker"

[[groups]]
  id = "sub-group-1"
  [groups.instances]
    count = 9
    percentage = 0.0

  [groups.run]
    [groups.run.test_params]
      alpha = "6"
      beta = "3"
      bs_strategy = "6"
      bucket_size = "10"
      group_order = "1"
      timeout_secs = "600"

[[groups]]
  id = "sub-group-2"
  [groups.instances]
    count = 9
    percentage = 0.0

  [groups.run]
    [groups.run.test_params]
      alpha = "6"
      beta = "3"
      bs_strategy = "6"
      bucket_size = "10"
      group_order = "4"
      record_count = "1"
      timeout_secs = "600"

[[groups]]
  id = "sub-group-3"
  [groups.instances]
    count = 9
    percentage = 0.0

  [groups.run]
    [groups.run.test_params]
      alpha = "6"
      beta = "3"
      bs_strategy = "6"
      bucket_size = "10"
      group_order = "3"
      record_count = "1"
      timeout_secs = "600"

[[groups]]
  id = "sub-group-4"
  [groups.instances]
    count = 9
    percentage = 0.0

  [groups.run]
    [groups.run.test_params]
      alpha = "6"
      beta = "3"
      bs_strategy = "6"
      bucket_size = "10"
      group_order = "2"
      record_count = "1"
      timeout_secs = "600"

[[groups]]
  id = "sub-group-5"
  [groups.instances]
    count = 9
    percentage = 0.0

  [groups.run]
    [groups.run.test_params]
      alpha = "6"
      beta = "3"
      bs_strategy = "6"
      bucket_size = "10"
      group_order = "5"
      search_records = "true"
      timeout_secs = "600"

[[groups]]
  id = "sub-group-6"
  [groups.instances]
    count = 9
    percentage = 0.0

  [groups.run]
    [groups.run.test_params]
      alpha = "6"
      beta = "3"
      bootstrapper = "true"
      bs_strategy = "6"
      bucket_size = "10"
      group_order = "0"
      timeout_secs = "600"

[[groups]]
  id = "sub-group-7"
  [groups.instances]
    count = 9
    percentage = 0.0

  [groups.run]
    [groups.run.test_params]
      alpha = "6"
      beta = "3"
      bs_strategy = "6"
      bucket_size = "10"
      group_order = "7"
      record_count = "1"
      timeout_secs = "600"

[[groups]]
  id = "sub-group-8"
  [groups.instances]
    count = 9
    percentage = 0.0

  [groups.run]
    [groups.run.test_params]
      alpha = "6"
      beta = "3"
      bs_strategy = "6"
      bucket_size = "10"
      group_order = "8"
      record_count = "1"
      timeout_secs = "600"

[[groups]]
  id = "sub-group-9"
  [groups.instances]
    count = 9
    percentage = 0.0

  [groups.run]
    [groups.run.test_params]
      alpha = "6"
      beta = "3"
      bs_strategy = "6"
      bucket_size = "10"
      group_order = "9"
      record_count = "1"
      timeout_secs = "600"

[[groups]]
  id = "sub-group-10"
  [groups.instances]
    count = 9
    percentage = 0.0

  [groups.run]
    [groups.run.test_params]
      alpha = "6"
      beta = "3"
      bs_strategy = "6"
      bucket_size = "10"
      group_order = "10"
      record_count = "1"
      timeout_secs = "600"

[[groups]]
  id = "pub-1"
  [groups.instances]
    count = 1
    percentage = 0.0

  [groups.run]
    [groups.run.test_params]
      alpha = "6"
      beta = "3"
      bootstrapper = "true"
      bs_strategy = "6"
      bucket_size = "10"
      group_order = "11"
      timeout_secs = "600"

[[groups]]
  id = "pub-2"
  [groups.instances]
    count = 1
    percentage = 0.0

  [groups.run]
    [groups.run.test_params]
      alpha = "6"
      beta = "3"
      bootstrapper = "true"
      bs_strategy = "6"
      bucket_size = "10"
      group_order = "12"
      timeout_secs = "600"

[[groups]]
  id = "pub-3"
  [groups.instances]
    count = 1
    percentage = 0.0

  [groups.run]
    [groups.run.test_params]
      alpha = "6"
      beta = "3"
      bootstrapper = "true"
      bs_strategy = "6"
      bucket_size = "10"
      group_order = "13"
      timeout_secs = "600"

[[groups]]
  id = "pub-4"
  [groups.instances]
    count = 1
    percentage = 0.0

  [groups.run]
    [groups.run.test_params]
      alpha = "6"
      beta = "3"
      bootstrapper = "true"
      bs_strategy = "6"
      bucket_size = "10"
      group_order = "14"
      timeout_secs = "600"

[[groups]]
  id = "pub-5"
  [groups.instances]
    count = 1
    percentage = 0.0

  [groups.run]
    [groups.run.test_params]
      alpha = "6"
      beta = "3"
      bootstrapper = "true"
      bs_strategy = "6"
      bucket_size = "10"
      group_order = "15"
      timeout_secs = "600"

[[groups]]
  id = "pub-6"
  [groups.instances]
    count = 1
    percentage = 0.0

  [groups.run]
    [groups.run.test_params]
      alpha = "6"
      beta = "3"
      bootstrapper = "true"
      bs_strategy = "6"
      bucket_size = "10"
      group_order = "16"
      timeout_secs = "600"

[[groups]]
  id = "pub-7"
  [groups.instances]
    count = 1
    percentage = 0.0

  [groups.run]
    [groups.run.test_params]
      alpha = "6"
      beta = "3"
      bootstrapper = "true"
      bs_strategy = "6"
      bucket_size = "10"
      group_order = "17"
      timeout_secs = "600"

[[groups]]
  id = "pub-8"
  [groups.instances]
    count = 1
    percentage = 0.0

  [groups.run]
    [groups.run.test_params]
      alpha = "6"
      beta = "3"
      bootstrapper = "true"
      bs_strategy = "6"
      bucket_size = "10"
      group_order = "18"
      timeout_secs = "600"

[[groups]]
  id = "pub-9"
  [groups.instances]
    count = 1
    percentage = 0.0

  [groups.run]
    [groups.run.test_params]
      alpha = "6"
      beta = "3"
      bootstrapper = "true"
      bs_strategy = "6"
      bucket_size = "10"
      group_order = "19"
      timeout_secs = "600"

[[groups]]
  id = "pub-10"
  [groups.instances]
    count = 1
    percentage = 0.0

  [groups.run]
    [groups.run.test_params]
      alpha = "6"
      beta = "3"
      bootstrapper = "true"
      bs_strategy = "6"
      bucket_size = "10"
      group_order = "20"
      timeout_secs = "600"