[metadata]
  name = "contentps-test"
  author = "pedroaston"

[global]
  plan = "contentps-test"
  case = "1st-test"
  total_instances = 17
  builder = "docker:go"
  runner = "local:docker"

[[groups]]
  id = "portugal-surf-sub"
  [groups.instances]
    count = 3
    percentage = 0.0

  [groups.run]
    [groups.run.test_params]
      alpha = "6"
      beta = "3"
      bs_strategy = "6"
      bucket_size = "10"
      group_order = "1"
      latency = "10"
      timeout_secs = "600"

[[groups]]
  id = "portugal-soccer-sub"
  [groups.instances]
    count = 3
    percentage = 0.0

  [groups.run]
    [groups.run.test_params]
      alpha = "6"
      beta = "3"
      bs_strategy = "6"
      bucket_size = "10"
      group_order = "4"
      latency = "10"
      record_count = "1"
      timeout_secs = "600"

[[groups]]
  id = "surf-bali-sub"
  [groups.instances]
    count = 2
    percentage = 0.0

  [groups.run]
    [groups.run.test_params]
      alpha = "6"
      beta = "3"
      bs_strategy = "6"
      bucket_size = "10"
      group_order = "3"
      latency = "10"
      record_count = "1"
      timeout_secs = "600"

[[groups]]
  id = "surf-bali-trip-price"
  [groups.instances]
    count = 2
    percentage = 0.0

  [groups.run]
    [groups.run.test_params]
      alpha = "6"
      beta = "3"
      bs_strategy = "6"
      bucket_size = "10"
      group_order = "2"
      latency = "10"
      record_count = "1"
      timeout_secs = "600"

[[groups]]
  id = "surf-trip-price-1"
  [groups.instances]
    count = 2
    percentage = 0.0

  [groups.run]
    [groups.run.test_params]
      alpha = "6"
      beta = "3"
      bs_strategy = "6"
      bucket_size = "10"
      group_order = "5"
      latency = "10"
      n_find_peers = "5"
      search_records = "true"
      timeout_secs = "600"

[[groups]]
  id = "surf-trip-price-2"
  [groups.instances]
    count = 2
    percentage = 0.0

  [groups.run]
    [groups.run.test_params]
      alpha = "6"
      beta = "3"
      bootstrapper = "true"
      bs_strategy = "6"
      bucket_size = "10"
      group_order = "0"
      latency = "10"
      timeout_secs = "600"

[[groups]]
  id = "ipfs-pub-1"
  [groups.instances]
    count = 1
    percentage = 0.0

  [groups.run]
    [groups.run.test_params]
      alpha = "6"
      beta = "3"
      bootstrapper = "true"
      bs_strategy = "6"
      bucket_size = "10"
      group_order = "6"
      latency = "10"
      timeout_secs = "600"

[[groups]]
  id = "portugal-surf-pub"
  [groups.instances]
    count = 1
    percentage = 0.0

  [groups.run]
    [groups.run.test_params]
      alpha = "6"
      beta = "3"
      bootstrapper = "true"
      bs_strategy = "6"
      bucket_size = "10"
      group_order = "7"
      latency = "10"
      timeout_secs = "600"

[[groups]]
  id = "ipfs-pub-2"
  [groups.instances]
    count = 1
    percentage = 0.0

  [groups.run]
    [groups.run.test_params]
      alpha = "6"
      beta = "3"
      bootstrapper = "true"
      bs_strategy = "6"
      bucket_size = "10"
      group_order = "8"
      latency = "10"
      timeout_secs = "600"